main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "portfolio/", views.PortfolioListView.as_view(), name="portfolio-list"
    ),
    path(
        "portfolio/<str:slug>",
        views.PortfolioDetailView.as_view(),
        name="portfolio-detail",
    ),
    path("contact/", views.ContactFormView.as_view(), name="contact"),
]

resume/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path, re_path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "favicon.ico",
        RedirectView.as_view(
            url=staticfiles_storage.url("images/favicon.ico")
        ),
    ),
]

urlpatterns += i18n_patterns(
    path("", include("main.urls", namespace="main")),
)

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [re_path(r"^rosetta/", include("rosetta.urls"))]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

main/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    class JobStatusChoices(models.IntegerChoices):
        full_time = 1, _("Full time job")
        part_time = 2, _("Part-time job")
        busy = 3, _("Busy")

    class JobTypeChoices(models.IntegerChoices):
        remote = 1, _("Remote work")
        daily_commute = 2, _("Daily Commute")

    photo = models.ImageField(_("Photo"), upload_to="photo/")
    citizenship = models.CharField(
        _("Citizenship"), default="Uzbekistan", max_length=32
    )
    city = models.CharField(_("City"), default="Tashkent", max_length=32)
    description = RichTextField(_("Description"))
    birth_date = models.DateField(_("Birth Date"), default="2003-12-11")
    job_title = models.CharField(
        _("Job Title"), max_length=128, default="Python backend developer"
    )
    job_status = models.IntegerField(
        _("Job Status"), choices=JobStatusChoices.choices, default=1
    )
    job_type = models.IntegerField(
        _("Job Type"), choices=JobTypeChoices.choices, default=1
    )
    ready_to_relocate = models.BooleanField(
        _("Ready To Relocate"), default=False
    )

    def save(self, *args, **kwargs):
        self.pk = self.id = 1
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")


class Skills(models.Model):
    name = models.CharField(_("Name"), max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Skill")
        verbose_name_plural = _("Skills")


class WorkExperience(models.Model):
    start = models.DateField(_("Start date"))
    title = models.CharField(_("Title"), max_length=128)
    description = RichTextField(_("Description"))
    end = models.DateField(_("End date"), null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.start < self.end:
            super().save(*args, **kwargs)
        else:
            raise ValidationError(_("The start date should be earlier than end date"))

    class Meta:
        verbose_name = _("Work Experience")
        verbose_name_plural = _("Work Experience")
        ordering = ("start",)


class Education(models.Model):
    institute = models.CharField(_("Institute"), max_length=128)
    faculty = models.CharField(_("Faculty"), max_length=128)
    specialization = models.CharField(_("Specialization"), max_length=128)
    is_completed = models.BooleanField(_("Is Completed"), default=True)

    def __str__(self):
        return self.institute

    class Meta:
        verbose_name = _("Education")
        verbose_name_plural = _("Education")


class Languages(models.Model):
    class LevelChoices(models.IntegerChoices):
        beginner = 1, _("beginner")
        pre_intermediate = 2, _("pre-intermediate")
        intermediate = 3, _("intermediate")
        upper_intermediate = 4, _("upper intermediate")
        native = 5, _("native speaker")

    name = models.CharField(_("Name"), max_length=128)
    level = models.IntegerField(
        _("Level"), default=1, choices=LevelChoices.choices
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Language")
        verbose_name_plural = _("Languages")


class Portfolio(models.Model):
    title = models.CharField(_("Title"), max_length=128)
    short_description = models.CharField(_("Short Description"), max_length=64)
    body = RichTextField(_("Body"), blank=True, null=True)
    image = models.ImageField(_("Image"), upload_to="portfolio/")
    technologies = models.ManyToManyField(
        Skills, verbose_name=_("Technologies")
    )
    slug = models.SlugField(_("Slug"), unique=True, max_length=32)
    created_at = models.DateField(_("Created at"))
    is_active = models.BooleanField(_("Is Active"), default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("main:portfolio-detail", args=[self.slug])

    class Meta:
        verbose_name_plural = _("Portfolio")
        verbose_name = _("Portfolio")
        ordering = ("created_at",)


class Contact(models.Model):
    from_whom = models.CharField(_("From Whom"), max_length=64)
    title = models.CharField(_("Title"), max_length=128)
    message = models.TextField(_("Message"), max_length=1024)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)

    def __str__(self):
        return self.from_whom

    class Meta:
        verbose_name = _("Contact")
        verbose_name_plural = _("Contacts")

main/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from . import models


class ContactForm(forms.ModelForm):
    from_whom = forms.CharField(
        label=_("From Whom"),
        min_length=4,
        max_length=64,
        widget=forms.TextInput(
            attrs={
                "class": "form-control mb-3",
                "placeholder": _("Enter site/email"),
            }
        ),
    )
    title = forms.CharField(
        label=_("Title"),
        min_length=4,
        max_length=128,
        widget=forms.TextInput(
            attrs={
                "class": "form-control mb-3",
                "placeholder": _("Enter title"),
            }
        ),
    )
    message = forms.CharField(
        label=_("Message"),
        min_length=4,
        max_length=128,
        widget=forms.Textarea(
            attrs={
                "class": "form-control mb-3",
                "placeholder": _("Enter message"),
                "rows": "3",
                "cols": "5",
            }
        ),
    )

    class Meta:
        model = models.Contact
        fields = "__all__"

main/views.py
from dateutil import relativedelta
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import get_list_or_404, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import DetailView, FormView, ListView

from . import forms, models
from .models import Portfolio

User = get_user_model()


class IndexView(View):
    template_name = "main/index.html"

    def get(self, request, *args, **kwargs):
        age = relativedelta.relativedelta(
            timezone.now().date(), User.objects.first().birth_date
        ).years
        work_experience = models.WorkExperience.objects.all()
        skills = models.Skills.objects.all()
        education = models.Education.objects.all()
        languages = models.Languages.objects.all()
        context = {
            "age": age,
            "work_experience": work_experience,
            "skills": skills,
            "education": education,
            "languages": languages,
        }
        return render(request, self.template_name, context)


class PortfolioListView(ListView):
    model = Portfolio
    template_name = "main/portfolio_list.html"
    context_object_name = "portfolio"

    def get_queryset(self):
        self.search = self.request.GET.get("q", None)
        if self.search:
            portfolio = get_list_or_404(
                self.model, is_active=True, technologies__pk__in=self.search
            )
            return portfolio
        else:
            return self.model.objects.filter(is_active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tech_name"] = models.Skills.objects.filter(
            pk=self.search
        ).first()
        return context


class PortfolioDetailView(DetailView):
    model = Portfolio
    template_name = "main/portfolio_detail.html"
    context_object_name = "project"

    def get_queryset(self):
        return self.model.objects.filter(is_active=True)


class ContactFormView(FormView):
    template_name = "main/contact.html"
    form_class = forms.ContactForm
    success_url = reverse_lazy("main:index")

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request, _("Thank you. I will be in touch soon.")
        )
        return super().form_valid(form)

templates/main/base.html
{% load static i18n %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}{% trans 'Main' %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'dependencies/bootstrap.min.css' %}">
  <script src="{% static 'dependencies/jquery-3.5.1.min.js' %}"></script>
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
  {% block stylesheet %}{% endblock %}
</head>
<body>
  <header class="header">
    <nav id="nav" class="navbar navbar-expand-sm navbar-light">
      <ul class="fs25 navbar-nav ms-auto fw-bold font-monospace">
        <li class="nav-item px-2">
          <a id="home" class="nav-link" href="{% url 'main:index' %}">
            {% trans 'На Главную' %}
          </a>
        </li>
        <li class="nav-item px-2">
          <a id="portfolio" class="nav-link" href="{% url 'main:portfolio-list' %}">
            {% trans 'Portfolio' %}
          </a>
        </li>
        <li class="nav-item px-2 pe-4">
          <a id="contact" class="nav-link" href="{% url 'main:contact' %}">
            {% trans 'Contact' %}
          </a>
        </li>
      </ul>
    </nav>
  </header>

  <div id="content" class="container-md">
    {% block content %} {% endblock content %}
  </div>

  <footer id="footer" class="fixed-bottom mt-5">
    <div class="container">
      <a class="h2 my-2 text-primary fw-bold d-flex justify-content-center text-decoration-none"
      href="mailto:{{me.email}}">
        📧{% trans 'Send me an email' %}
      </a>
      <h5 class="my-3 text-white text-center">
        {% trans 'Copyright' %} ©{% now 'Y' %} {% trans 'All rights reserved.' %}
      </h5>
    </div>
  </footer>

  <script>
    var request_path = '{{ request.path }}';
  </script>
  <script src="{% static 'main/js/base.js' %}"></script>

</body>
</html>

templates/main/contact.html
{% extends 'main/base.html' %}
{% load i18n %}
{% block title %}{% trans 'Contact me' %}{% endblock %}

{% block content %}

  <h1 class="my-5">{% trans 'Contact me' %}</h1>

  <div class="row py-4">
    <form method="post">
      {% csrf_token %}
      <label class="small fw-bold">{{ form.from_whom.label}}</label>
      {{ form.from_whom }}
      <label class="small fw-bold">{{ form.title.label}}</label>
      {{ form.title }}
      <label class="small fw-bold">{{ form.message.label}}</label>
      {{ form.message }}
      <button class="btn btn-primary my-2 px-5 fw-bold" type="submit">
        {% trans 'Submit' %}
      </button>
    </form>
  </div>

{% endblock %}

templates/main/index.html
{% extends 'main/base.html' %}
{% load static i18n %}
{% block title %}{% trans 'Main' %}{% endblock %}
{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'main/css/index.css' %}">
{% endblock %}

{% block content %}

  {% if messages %}

    <div class="alert alert-warning mt-3" role="alert">
      {% for message in messages  %}
        {% if message.tags == "success" %}
          <h4 class="{{ message.tags }}">{{ message }}</h4>
        {% endif %}
      {% endfor %}
    </div>

  {% endif %}

  <div id="profile-row" class="row mt-3">
    <div class="col m-3">
      <div id="profile-card" class="card">
        <div class="card-body">
           <div class="row">
             <div class="col-2 d-flex justify-content-center">
              <img id="profile-image" src="{{ me.photo.url }}">
             </div>
             <div class="col-10 m-auto align-middle">
               <h5>
                 {% trans 'Name' %}: {{ me.first_name }} {{ me.last_name }}
               </h5>
               <h5>{{ age }} {% trans 'years old (was born on' %} {{ me.birth_date }})</h5>
               <h5>
                 {% trans 'Citizenship' %}: {{ me.citizenship }}
               </h5>
               <h5>{{ me.city }},
                 {% if me.ready_to_relocate %}
                   {% trans 'ready to relocate' %}
                 {% else %}
                   {% trans 'not ready to relocate' %}
                 {% endif %}
               </h5>
             </div>
           </div>
        </div>
      </div>
    </div>
    <div class="px-4">

      <h1 class="fw-bold">{{ me.job_title }}</h1>
      <ul>
        {% if me.job_status == 3 %}
          <li class="h4">{% trans 'Busy' %}</li>
        {% else %}
          <li class="h4">{{ me.get_job_status_display }}, {{ me.get_job_type_display }}</li>
        {% endif %}
      </ul>
      <hr id="profile-hr" size="4">

      {% if work_experience %}

        <h2>
          <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" fill="currentColor" class="bi bi-briefcase-fill" viewBox="0 0 16 16">
            <path d="M6.5 1A1.5 1.5 0 0 0 5 2.5V3H1.5A1.5 1.5 0 0 0 0 4.5v1.384l7.614 2.03a1.5 1.5 0 0 0 .772 0L16 5.884V4.5A1.5 1.5 0 0 0 14.5 3H11v-.5A1.5 1.5 0 0 0 9.5 1h-3zm0 1h3a.5.5 0 0 1 .5.5V3H6v-.5a.5.5 0 0 1 .5-.5z"/>
            <path d="M0 12.5A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5V6.85L8.129 8.947a.5.5 0 0 1-.258 0L0 6.85v5.65z"/>
          </svg>
          <span class="fw-bold profile-headers">{% trans 'Work experience' %}</span>
        </h2>

        {% for work in work_experience %}
          <div class="row my-2">
            <div class="col-2">
              <span>{{ work.start }} - <br> {{ work.end }}</span>
            </div>
            <div class="col-10">
              <h3>{{ work.title }}</h3>
              <h6>{{ work.description|safe }}</h6>
            </div>
          </div>
        {% endfor %}
        <hr size="2">

      {% endif %}

      <h2>
        <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
        </svg>
        <span class="fw-bold profile-headers">{% trans 'Knowledge and Skills' %}</span>
      </h2>
      {% for skill in skills %}
        <a class="text-decoration-none" href="{% url 'main:portfolio-list' %}?q={{ skill.pk }}">
          <span class="btn profile-skill text-primary rounded-pill mx-2 mb-3">{{ skill.name }}</span>
        </a>
      {% endfor %}
      <hr size="2">

      <h2>
        <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
          <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
        </svg>
        <span class="fw-bold profile-headers">{% trans 'Education' %}</span>
      </h2>
      {% for institute in education %}
        <h4 class="ms-3 italic font-monospace">{{ institute.institute }}
          {% if institute.is_completed %}
            {% trans '(completed):' %}
          {% else %}
            {% trans '(studying):' %}
          {% endif %}
        </h4>
        <h5 class="ms-5">{{ institute.faculty }}, {{ institute.specialization }}</h5>
      {% endfor %}
      <hr size="2">

      <h2 class="fw-bold">
        <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" fill="currentColor" class="bi bi-translate" viewBox="0 0 16 16">
          <path d="M4.545 6.714 4.11 8H3l1.862-5h1.284L8 8H6.833l-.435-1.286H4.545zm1.634-.736L5.5 3.956h-.049l-.679 2.022H6.18z"/>
          <path d="M0 2a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v3h3a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-3H2a2 2 0 0 1-2-2V2zm2-1a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h7a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2zm7.138 9.995c.193.301.402.583.63.846-.748.575-1.673 1.001-2.768 1.292.178.217.451.635.555.867 1.125-.359 2.08-.844 2.886-1.494.777.665 1.739 1.165 2.93 1.472.133-.254.414-.673.629-.89-1.125-.253-2.057-.694-2.82-1.284.681-.747 1.222-1.651 1.621-2.757H14V8h-3v1.047h.765c-.318.844-.74 1.546-1.272 2.13a6.066 6.066 0 0 1-.415-.492 1.988 1.988 0 0 1-.94.31z"/>
        </svg>
        <span class="fw-bold profile-headers">{% trans 'Languages' %}</span>
      </h2>
      {% for language in languages %}
        <h4 class="ms-2">{{ language.name }} — {{ language.get_level_display }}</h4>
      {% endfor %}
      <hr class="mt-3" size="2">

      <h2 class="my-3 fw-bold">{% trans 'Additional information:' %}</h2>
      <h5>{{ me.description|safe }}</h5>

    </div>
  </div>
{% endblock %}

templates/main/portfolio_detail.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ project.title }} {% endblock %}
{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'main/css/portfolio_detail.css' %}">
{% endblock %}

{% block content %}
  <h1 class="text-center fw-bold my-3">{{ project.title }}</h1>
  <img id="project-image" class="img-fluid mb-4" src="{{ project.image.url }}">
  <div id="project-body" class="detail-project-body p-3">
    {{ project.body|safe }}
  </div>
  <blockquote class="blockquote text-end">
    <h3 class="p-2 mb-5 fw-bold">{{ project.created_at }}</h3>
  </blockquote>
{% endblock %}

templates/main/portfolio_list.html
{% extends 'main/base.html' %}
{% load static i18n %}
{% block title %}{% trans 'Portfolio' %}{% endblock %}
{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'main/css/portfolio.css' %}">
{% endblock %}

{% block content %}

  <h1 class="text-center my-3 font-monospace">{% trans 'Active projects' %}({{ portfolio.count }})</h1>
  {% if tech_name %}
    <h3>{% trans 'Search by' %} <b>{{ tech_name.name }}</b>:</h3>
  {% endif %}
  <div class="row">

    {% for project in portfolio %}

      <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">
        <div class="card service-wrapper rounded border-0 shadow p-4">
          <img src="{{ project.image.url }}" class="m-auto project-image">
          <div class="content mt-4">
            <a href="{% url 'main:portfolio-detail' project.slug %}" class="h5 text-decoration-none">{{ project.title }}</a>
            <p class="mt-3 mb-0">{{ project.short_description }}</p>
            <p class="text-muted mt-3 mb-0">{{ project.created_at }}</p>
          </div>
        </div>
      </div>

    {% endfor %}

  </div>

{% endblock %}